apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: backend
        image: mohammadtouqeer/todo-backend:v2
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:///./test.db"
        - name: JWT_SECRET
          value: "victory_secret_key_2026"
        command: ["/bin/sh"]
        args: ["-c", "cd /app && python -m uvicorn src.todo_app:app --host 0.0.0.0 --port 8000 --reload"]
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todo-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP